build:
  stage: build
  tags:
  - shell
  only:
  - build-FS-9776
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} .

test:
  stage: test
  tags:
  - shell
  only:
  - build-FS-9776
  script:
  - docker run --rm ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} /bin/bash -c 'npm test'

push:
  stage: deploy
  only:
  - build-FS-9776
  script:
  - docker push ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}

variables:
  PROJECT_TAG: "4.2.0"
