build:
  stage: build
  only:
  - tags
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  # No sounds
  - docker build --build-arg=WITH_SOUNDS=false -t ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} .
  - docker push ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}
  # With sounds
  - docker build --build-arg=WITH_SOUNDS=true  -t ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}-with-sounds .
  - docker push ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}-with-sounds

variables:
  PROJECT_TAG: "4.3.2-master"
