image: debian:unstable
build:
  stage: build
  only:
  - build-FS-9776.with-sounds
  before_script:
  - apt-get update && apt-get install -y --no-install-recommends docker.io
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} .
  - docker push ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}

variables:
  PROJECT_TAG: "4.2.1-with-sounds"
