build:
  stage: build
  only:
  - tags
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  # Build
  - docker build -t docker.freeswitch -f Dockerfile.debian .
  - docker build -t docker.freeswitch:with-sounds -f Dockerfile.debian.with-sounds .
  # Rename
  - docker tag docker.freeswitch             ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  - docker tag docker.freeswitch:with-sounds ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-with-sounds
  # Push
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-with-sounds

intermediary:
  stage: build
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  # No sounds
  - docker build -t docker.freeswitch -f Dockerfile.debian .
  # With sounds
  - docker build -t docker.freeswitch:with-sounds -f Dockerfile.debian.with-sounds .
