sudo: required
language: shell
services:
- docker

script:
  # No sounds
  - docker build --build-arg=WITH_SOUNDS=false -t "shimaore/docker.freeswitch:latest" .
  # With sounds
  - docker build --build-arg=WITH_SOUNDS=true  -t "shimaore/docker.freeswitch:latest-with-sounds" .

after_success:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - test -n "${TRAVIS_BRANCH}" && docker tag  "shimaore/docker.freeswitch:latest"             "shimaore/docker.freeswitch:${TRAVIS_BRANCH}"
  - test -n "${TRAVIS_BRANCH}" && docker tag  "shimaore/docker.freeswitch:latest-with-sounds" "shimaore/docker.freeswitch:${TRAVIS_BRANCH}-with-sounds"
  - test -n "${TRAVIS_BRANCH}" && docker push "shimaore/docker.freeswitch:${TRAVIS_BRANCH}"
  - test -n "${TRAVIS_BRANCH}" && docker push "shimaore/docker.freeswitch:${TRAVIS_BRANCH}-with-sounds"
  - test -n "${TRAVIS_TAG}" && docker tag  "shimaore/docker.freeswitch:latest"             "shimaore/docker.freeswitch:${TRAVIS_TAG}"
  - test -n "${TRAVIS_TAG}" && docker tag  "shimaore/docker.freeswitch:latest-with-sounds" "shimaore/docker.freeswitch:${TRAVIS_TAG}-with-sounds"
  - test -n "${TRAVIS_TAG}" && docker push "shimaore/docker.freeswitch:${TRAVIS_TAG}"
  - test -n "${TRAVIS_TAG}" && docker push "shimaore/docker.freeswitch:${TRAVIS_TAG}-with-sounds"
